name: Daily Email

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # This triggers the workflow daily at 12:00 AM UTC

permissions: # Global permissions configuration starts here
  contents: write # 'read' access to repository contents
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests redmail

      - name: Send email
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          USEREMAIL: ${{ secrets.USEREMAIL }}
        run: python main.py

      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -a -m "Add changes"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.TOKEN }}
          branch: main
          force_with_lease: true
